- packages/brain/src/calls/index.ts
- packages/brain/src/calls/validators.ts
- packages/common/src/routes.ts
- packages/common/src/types/api/validator/types.ts
Add `getExitValidators` and abstract logic with `exitValidators`
> Add `getExitValidators` 

- packages/brain/src/calls/validators.ts
- packages/brain/src/modules/apiClients/web3signer/index.ts
- packages/common/src/routes.ts
- packages/common/src/types/api/web3signer/types.ts
- packages/ui/src/components/Dialogs/ExitWarning.tsx
- packages/ui/src/components/Dialogs/KeystoresDeleteDialog.tsx
- packages/ui/src/components/Dialogs/KeystoresExitDialog.tsx
- packages/ui/src/components/ValidatorList/KeystoresDataGrid.tsx
- packages/ui/src/components/ValidatorList/ValidatorList.tsx
- packages/ui/src/utils/dataUtils.ts
Implement exit validators on frontend:
- Exit action
- Download exit signed for selected validators
> Implement exit validators on frontend

- packages/ui/src/ImportScreen.tsx
Disable import if keystore values:
- Tag
- Fee recipient
- password
> Disable import if no ( FeeRecipient || Tag || Password)

- packages/brain/src/modules/envs/index.ts
Add lodestar api token for mainnet and prater to match tokens in Lodestar prater and mainnet package
- https://github.com/dappnode/DAppNodePackage-Lodestar/blob/main/validator/security/api-token.txt
- https://github.com/dappnode/DAppNodePackage-Lodestar-Prater/blob/main/validator/api-token.txt
> Add lodestar api token for all networks

- packages/common/src/utils/index.ts
> Improve util checks

- packages/ui/src/components/ValidatorList/KeystoresDataGrid.tsx
Hide exit for gnosis and mainnet
> Hide exit if network!=prater

- packages/brain/src/calls/validators.ts
- packages/common/src/types/customValidators/types.ts
- packages/ui/src/components/ValidatorList/KeystoresDataGrid.tsx
Implement get withdrawal creds for each validator
> Implemen withdrawal creds

- packages/ui/src/App.tsx
- packages/ui/src/ImportScreen.tsx
- packages/ui/src/components/FileCards/FileCardList.tsx
- packages/ui/src/types.ts
In Gnosis there are no DVT/LSD technologies, so only tag "solo" should be allowed
> Only "solo" tag shown for Gnosis

- packages/ui/src/components/ValidatorList/KeystoresDataGrid.tsx
> Fix withdrawal addr typos

- packages/common/.mocharc.yaml
- packages/common/package.json
- packages/common/tests/unit/utils/addressValidation.unit.test.ts
1. Setup for tests in common package
2. Tests for ECDSA/BLS addresses for withdraws
> Create tests for common package

- packages/ui/src/components/ValidatorList/KeystoresDataGrid.tsx
Exit disabled if any tag of the selected rows is "rocketpool"
> Disable exit for Rocket Pool

- packages/brain/.env
- packages/brain/package.json
- packages/brain/src/calls/importValidators.ts
- packages/brain/src/modules/stakingProtocols/stakehouse/index.ts
- packages/brain/src/modules/stakingProtocols/stakehouse/types.ts
- packages/common/src/types/db/types.ts
- yarn.lock
Fee recipient is automatically calculated for StakeHouse
> Get fee recipient for StakeHouse

- packages/ui/src/components/Dialogs/EditFeesDialog.tsx
Edit dialog is now handling all possibilities and errors for subscription/unsubscription
> Handle (un)subscription in FR edit dialog

- packages/brain/src/modules/envs/index.ts
Set nimbus beacon chain to port 4500
> Fix exit on Nimbus Prater

- packages/brain/src/calls/importValidators.ts
- packages/brain/src/modules/stakingProtocols/stakehouse/index.ts
Fee Recipient automatic get process was throwing errors that were not properly handled
> Fix automatic FR calculation

- packages/brain/src/calls/importValidators.ts
> Logger for fee recipient

- packages/brain/src/modules/envs/index.ts
- packages/brain/tests/unit/modules/apiClients/fetchValidatorIndex.unit.test.ts
- packages/ui/src/params.ts
Check it @dsimog01 
Fixed #250
> Replace beacon.gnosischain with new url gnosischa.in

- packages/ui/public/index.html
> Change favicon

- packages/ui/src/components/Dialogs/ExitWarning.tsx
- packages/ui/src/components/Dialogs/KeystoresExitDialog.tsx
- packages/ui/src/components/ValidatorList/ValidatorList.tsx
Remove gnosis exit warning and unused var
> Remove gnosis exit warning

- .github/workflows/main.yml
- .github/workflows/release.yml
- package.json
> update gha and engines

- packages/brain/src/calls/getStakerConfig.ts
- packages/brain/src/index.ts
- packages/brain/src/modules/db/index.ts
- packages/brain/src/modules/envs/index.ts
- packages/brain/tests/unit/modules/db/index.unit.test.ts
- packages/common/src/types/network/types.ts
Remove fee recipient as global env
> [ Breaking change ] Remove fee recipient as global env

- packages/brain/src/index.ts
- packages/brain/src/modules/apiServers/ui/index.ts
Allow origin in brain UI, otherwise in current version of google chrome in MAC raises CORS error due to accessing a private IP
> Allow origin in brain UI

- packages/brain/src/modules/envs/index.ts
Adding in envs nimbus-gnosis as consensus client case
> Add nimbus-gnosis as consensus client

- packages/ui/src/components/Dialogs/EditFeesDialog.tsx
- packages/ui/src/components/ValidatorList/SmoothStatus.tsx
Converting to lowerCase Smooth's fee recipient when comparing it while checking Smooth Status and when changing FR from validator to Smooth's FR
> Smooth FR case sensitive fix

- packages/brain/package.json
- packages/common/package.json
Fixes the following error in dev mode:
```
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /app/packages/common/src/index.ts
```
> Fix brain dev mode

- docker-compose-dev.yml
- packages/brain/.env
Updated development envs to use `holesky` instead of `prater`
Also fixed typo (Missing "_GLOBAL" in global envs)
> Update development envs to holesky network

- packages/brain/tests/unit/modules/apiClients/fetchValidatorIndex.unit.test.ts
Fixed #310 @pablomendezroyo prater.beaconcha.in isn't running anymore. Merge this commit before #309 and update #309 with main for successful testing
> Fix #310 Update fetchValidatorIndex.unit.test.ts removing prater

- packages/brain/src/params.ts
Update domain to validators-proofs.dappnode.io/
> Update domain to validators-proofs.dappnode.io/

- packages/brain/src/calls/importValidators.ts
- packages/common/src/params.ts
- packages/common/src/types/db/types.ts
Add not editable fee recipient for lido tag.
> Add fee recipient for lido tag

- packages/brain/src/modules/apiClients/beaconchain.ts
- packages/common/src/types/api/beaconchain/types.ts
Add getBlockAttestations endpoint to beaconchain
> Add getBlockAttestations endpoint to beaconchain

- packages/brain/src/modules/apiClients/beaconchain.ts
- packages/common/src/types/api/beaconchain/types.ts
Add getAttestationsRewards endpoint to beaconchain
> Add getAttestationsRewards endpoint to beaconchain

- tsconfig.json
Use latest ecmascript version in target and module
> Use latest ecmascript version in target and module

- packages/brain/src/index.ts
- packages/brain/src/modules/cron/index.ts
- packages/brain/src/modules/cron/trackValidatorsPerformance.ts
Start cron at the beggining pf the epoch
> Start cron at the beggining pf the epoch

- packages/brain/src/modules/apiClients/postgres/index.ts
- packages/brain/test/unit/modules/apiClients/postgresClient.unit.test.ts
Add delete database table method
> Add delete database table method

- packages/brain/src/modules/apiClients/postgres/index.ts
- packages/brain/test/unit/modules/apiClients/postgresClient.unit.test.ts
Reverts dappnode/StakingBrain#332
> Revert "Add delete database table method"

- packages/brain/src/modules/apiClients/postgres/index.ts
- packages/brain/test/unit/modules/apiClients/postgresClient.unit.test.ts
Add delete table from database method
> Add delete table from database method

- packages/brain/src/modules/cron/trackValidatorsPerformance.ts
- packages/brain/src/modules/db/index.ts
- packages/brain/src/modules/db/types.ts
Save validator indexes in db to avoid having to retrieving them every single time are needed
> Save validator indexes in db

- packages/brain/src/index.ts
- packages/brain/src/modules/cron/reloadValidators/deleteDbPubkeysNotInSigner.ts
- packages/brain/src/modules/cron/reloadValidators/deleteSignerPubkeysNotInDb.ts
- packages/brain/src/modules/cron/reloadValidators/deleteValidatorPubkeysNotInDb.ts
- packages/brain/src/modules/cron/reloadValidators/index.ts
- packages/brain/src/modules/cron/reloadValidators/logPrefix.ts
- packages/brain/src/modules/cron/reloadValidators/postValidatorPubkeysFromDb.ts
- packages/brain/src/modules/cron/reloadValidators/postValidatorsFeeRecipientsFromDb.ts
- packages/brain/src/modules/cron/sendProofsOfValidation/getProofsOfValidation.ts
- packages/brain/src/modules/cron/sendProofsOfValidation/index.ts
- packages/brain/src/modules/cron/sendProofsOfValidation/logPrefix.ts
- packages/brain/src/modules/cron/trackValidatorsPerformance/index.ts
- packages/brain/src/modules/cron/trackValidatorsPerformance/insertPerformanceData.ts
Reorg track validators performance cron:
- Add log prefix
- Resolve promise with blockheader
> Reorg track validators performance cron 

- packages/brain/src/index.ts
- packages/brain/src/modules/apiClients/postgres/error.ts
- packages/brain/src/modules/apiClients/postgres/index.ts
- packages/brain/src/modules/cron/trackValidatorsPerformance/index.ts
- packages/brain/test/unit/modules/apiClients/postgresClient.unit.test.ts
Fix postgres db initialization splitting queries into single ones
> Fix postgres db initialization

- packages/brain/src/index.ts
- packages/brain/src/modules/cron/trackValidatorsPerformance/index.ts
Execute cron once every epoch within the first 10% of time of the epoch. Also use the epoch change to track when to exit the loop
> Execute cron once every epoch within the first 10% of time of the epoch 

- packages/brain/src/modules/apiClients/beaconchain/index.ts
- packages/brain/src/modules/apiClients/beaconchain/types.ts
- packages/brain/src/modules/cron/trackValidatorsPerformance/getBlockProposalStatusMap.ts
- packages/brain/src/modules/cron/trackValidatorsPerformance/index.ts
- packages/brain/test/unit/modules/ cron/trackValidatorsPerformance/getActiveValidatorsLoadedInBrain.unit.test.ts
- packages/brain/test/unit/modules/ cron/trackValidatorsPerformance/getBlockProposalStatusMap.unit.test.ts
Add unit testing to trackValidatorsPerformance cron module
> Add unit testing to trackValidatorsPerformance cron module

- packages/brain/src/modules/validatorsDataIngest/getClientsUsedPerIntervalsMap.ts
- packages/brain/src/modules/validatorsDataIngest/index.ts
- packages/brain/test/unit/modules/validatorsDataIngest/getAttestationSuccessRate.unit.test.ts
- packages/brain/test/unit/modules/validatorsDataIngest/getAttestationSuccessRatePerClients.unit.test.ts
- packages/brain/test/unit/modules/validatorsDataIngest/getClientsUsedPerIntervalsMap.unit.test.ts
- packages/brain/test/unit/modules/validatorsDataIngest/getIntervalsEpochs.unit.test.ts
- packages/brain/test/unit/modules/validatorsDataIngest/getStartAndEndEpochs.unit.test.ts
Add missing test to validators data ingest module
> Add missing test to validators data ingest. WIP

- packages/brain/src/modules/cron/trackValidatorsPerformance/trackValidatorsPerformance.ts
Use finality endpoint instead of header
> Use finality endpoint

- packages/brain/src/modules/apiClients/postgres/index.ts
Update SQL query to update if exists. It is important to call only this function when:
- Call with data and nothing in db
- Call with data and error in db
- Call with error and nothing in db
- Call with new error and error already in db
Also create table with lodestar client
> Update SQL query to update if exists

- packages/brain/src/calls/fetchValidatorsPerformanceData.ts
- packages/brain/src/index.ts
- packages/brain/src/modules/apiClients/postgres/index.ts
- packages/brain/src/modules/validatorsDataIngest/index.ts
- packages/brain/src/modules/validatorsDataIngest/types.ts
- packages/brain/src/types.ts
- packages/ui/src/socket/types.ts
Add epoch to block proposed and add endpoint to rpc socket in frontend
> Add epoch to block proposed 

- docker-compose-dev.yml
- packages/brain/src/modules/cron/trackValidatorsPerformance/sendValidatorsPerformanceNotifications.ts
Fix source comparision and rename container in dev compose
> Fix source comparision and rename container in dev compose

- packages/brain/src/modules/apiClients/postgres/index.ts
> Add att ideal reward column

- packages/brain/package.json
- packages/brain/src/modules/apiServers/launchpad/routes/feeRecipients/route.ts
- yarn.lock
Bump express to ^5.0.0 and fix return type
> Bump express to ^5.0.0

- packages/brain/src/modules/logger/index.ts
Fix logger module for error logging messages
> Fix logger module for error

- packages/brain/src/modules/cron/reloadValidators/postValidatorsFeeRecipientsFromDb.ts
Compare feerecipient lowercase in cron
> Compare feerecipient lowercase

- packages/brain/src/modules/apiClients/signer/index.ts
- packages/brain/src/modules/apiClients/standard.ts
Add text plain header to `upcheck` request. See https://consensys.github.io/web3signer/web3signer-eth2.html#tag/Server-Status
> Add text plain header to `/upcheck` request

- packages/common/src/utils/index.ts
change regex so both 0x01 and 0x02 withdrawal credentials are valid withdrawable ecdsa keys
> add 0x02 as valid ecdsa key
