dappnode/StakingBrain

packages/ui/src/components/ValidatorList/KeystoresDataGrid.tsx

Exit was hidden for mainnet and gnosis. Taking it back

Show exit on all networks

---

packages/brain/src/modules/apiServers/ui/index.ts

`importValidators` was generating too much noise when being called via RPC, so it is silent now

Silent logger for importValidators

---

packages/brain/package.json
yarn.lock

StakeHouse version is changed from `^3.3.0` to `3.3.0`, as it is generating build errors

Fix StakeHouse lib version

---

packages/brain/package.json
yarn.lock

Latest stakehouse lib fixes the issue of fee recipient not being retrieved properly from LSD network.

Update stakehouse lib

---

packages/brain/src/calls/exitValidators.ts
packages/brain/src/modules/apiClients/web3signer/index.ts
packages/common/src/types/api/web3signer/types.ts

Some users reported not being able to exit their prater validator and this fixes that issue. The problem was that we were parsing a signer response as a string, which was, in fact, an object like `{signature: string}`

Fix wrong parsing in exit

---

packages/brain/src/modules/apiClients/web3signer/index.ts

We are actually using `/healthcheck` instead of `/upcheck`

Update healthcheck link

---

packages/brain/src/index.ts
packages/brain/src/modules/apiClients/beaconchain/index.ts

The gnosis chain uses 16 slots per epoch instead of 32 (Ethereum). This was causing issues for exits signatures
See contract deployment https://docs.gnosischain.com/specs/gbc/

Set 16 slots per epoch in gnosis beaconchain API

---

packages/brain/src/modules/cron/index.ts

Added a healthcheck on reloadValidators() at the very beginning of it. This is done to avoid unintended DB modifications when the web3signer is down and cant load correctly all validators. We must assure that all data is correct and loaded correctly when trying to persist the truth in our DB.
Also improved a bit error handling by logging an error if `if (e instanceof ApiError && e.code) {` doesnt check.
This should be tested thoroughly

Add signer api healthcheck on realoadValidators

---

packages/brain/src/modules/apiClients/index.ts

StakingBrain `request()` method had no handling for a response with an error. This made the code to be stuck when an error was returned, since there was no `reject()` or `resolve()` for that case. 
This bug was found by brain UI being stuck when trying to delete a validator while using Lodestar holesky as a consensus client, since it's validator API seems to be failing when trying to delete a fee_recipient for a given pubkey

Add error handling on response when doing requests

---

packages/brain/package.json
packages/ui/package.json
yarn.lock

By adding these dependencies to `devDependencies` we remove the warnings that are shown during install/build

Remove build warnings

---

packages/common/src/params.ts
packages/ui/src/ImportScreen.tsx
packages/ui/src/components/Dialogs/EditFeesDialog.tsx
packages/ui/src/components/ValidatorList/ValidatorList.tsx
packages/ui/src/params.ts
packages/ui/src/types.ts
packages/ui/src/utils/addresses.ts

- Adding stepper on editing FR from selected validators when "Set Dappnode MEV Smoothing Pool Fee Recipient" is checked in ValidatorsList

Integrate Smooth Fee recipient changes

---

packages/brain/src/modules/apiServers/launchpad/index.ts

Removing keystores from brain is now allowed externally for the packages whitelisted in CORS

Remove keystores allowed on launchpad

---

packages/ui/src/components/ValidatorList/KeystoresDataGrid.tsx

When all the selected validators' types are non editable fee recipient tags, the editing fee recipient button from the Validators list is disabled

Disabling edit FR btn when all selected validators are not editable

---

packages/brain/src/modules/envs/index.ts

Reverts dappnode/StakingBrain#299
After updating wallet path in validator service of Prysm package, we could avoid chaging the auth token

Revert "Update Prysm auth token"

---

packages/brain/src/calls/importValidators.ts
packages/brain/src/modules/apiClients/validator/index.ts

Prysm v5.0.0 validator API returns status in upper case (e.g. IMPORTED) so this needs to be handled at the moment of handling the response in the brain

Validator API response status to lower case

---

packages/brain/src/modules/apiServers/launchpad/routes/keystores/route.ts

Now the brain can handle GET requests to  `/eth/v1/keystores`. It essentially proxies the request to the web3signer. This will be used by the Stakewise package

Add proxy to keystores get

---

packages/common/src/utils/index.ts

Fixed #263 @pablomendezroyo @dappnodedev Give some ❤️ to this change 🙏 Generate the web3signer-holesky package with this change is mandatory for publishing rocketpool-testnet. RP changed the fee recipient address when they changed the network from prater to holesky. Right now the smoothing pool address isn't equal to mainnet

Fix #263 Update index.ts allowing rocketpool validators to set a custom fee recipient address

---

docker-compose-dev.yml
packages/ui/src/App.tsx
packages/ui/src/ImportScreen.tsx

- Added MEV warning when user has a validator imported with "Lido" tag but Mev-Boost is not installed:
- Updated "submit keystore" disabled button to be disabled when any tags, passwords or editable fee recipients are empty, aswell as when "Lido" tag and no mevboost is detected
- Fixed minor bugs regarding "Use same password/FR/Tag": switch was not applying same values if user previously selected different tags/fee recipient

Add MEV warning on keystore lido imports

---

packages/brain/package.json
packages/brain/src/calls/exitValidators.ts
packages/brain/src/modules/apiClients/beaconcha.ts
packages/brain/src/modules/apiClients/beaconchain.ts
packages/brain/src/modules/apiClients/validator.ts
packages/common/package.json
packages/common/src/types/api/beaconchain/types.ts
packages/common/src/types/api/validator/types.ts
yarn.lock

Add missing endpoints to validator and beaconchain API clients.
- Beaconchain
- `getStateFinalityCheckpoints`
- Validator:
- `getAttesterDuties`
- `getProposerDuties`

Add missing endpoints to validator and beaconchain API clients required to calculate validator performance

---

packages/brain/src/modules/apiClients/beaconchain/index.ts
packages/brain/src/modules/apiClients/beaconchain/types.ts
packages/brain/src/modules/apiClients/postgres/types.ts
packages/brain/src/modules/cron/trackValidatorsPerformance.ts

Checking the block proposal status can be broken down into two steps:
- Check Proposer Duties: Did my validator X have the responsibility to propose a block during this epoch? If yes, for which slot?
- Check if the Duty was Fulfilled: Was a block proposed during the assigned slot? Was my validator the one that proposed it?

add block proposal duties into db

---

packages/brain/src/index.ts
packages/brain/src/modules/cron/trackValidatorsPerformance/index.ts
packages/brain/src/modules/cron/trackValidatorsPerformance/insertPerformanceData.ts

cron is executed each minute. If the current epoch hasnt been processed, the cron calls `trackValidatorsPerformance()`, it doesnt matter if the epoch is about to end.
TODO: figure a way to store latest processed epoch that persists when brain container is stopped

refactor cron

---

packages/brain/src/modules/config/networks/gnosis.ts
packages/brain/src/modules/config/networks/holesky.ts
packages/brain/src/modules/config/networks/lukso.ts
packages/brain/src/modules/config/networks/mainnet.ts
packages/brain/src/modules/config/networks/prater.ts

Teku uses HTTPS due to the tls certificate in the validator URL

Use protocol https in teku

---

packages/brain/src/modules/config/networks/gnosis.ts
packages/brain/src/modules/config/networks/holesky.ts
packages/brain/src/modules/config/networks/lukso.ts
packages/brain/src/modules/config/networks/mainnet.ts
packages/brain/src/modules/config/networks/prater.ts
packages/brain/src/modules/config/networks/tlsCert.ts

Fix tls certificate for teku validator API. It was missing the network as string when resolvin the path of the tls certificate

Fix tls certificate for teku validator API

---

packages/brain/src/modules/config/getTlsCert.ts
packages/brain/src/modules/config/getValidatorToken.ts
packages/brain/src/modules/config/index.ts
packages/brain/src/modules/config/networks/gnosis.ts
packages/brain/src/modules/config/networks/holesky.ts
packages/brain/src/modules/config/networks/index.ts
packages/brain/src/modules/config/networks/lukso.ts
packages/brain/src/modules/config/networks/mainnet.ts
packages/brain/src/modules/config/networks/prater.ts
packages/brain/src/modules/config/types.ts

Split the configuration of the bain from the configuration for each network.
Also fix the Teku validator URL since it cannot be used the fullnodea alias due to the certificate. It is required to update the certificate in both: validator teku and brain, at the same time

Split config brain and config network

---

packages/brain/src/modules/apiClients/beaconchain/error.ts
packages/brain/src/modules/apiClients/postgres/index.ts
packages/brain/src/modules/apiClients/postgres/types.ts
packages/brain/src/modules/cron/trackValidatorsPerformance/error.ts
packages/brain/src/modules/cron/trackValidatorsPerformance/insertPerformanceData.ts
packages/brain/src/modules/cron/trackValidatorsPerformance/trackValidatorsPerformance.ts
packages/brain/src/modules/validatorsDataIngest/getAttestationSuccessRate.ts

Store `trackValidatorsPerformance`error in db:
- If the epoch was processed WITHOUT an error then skip cron iteration
- If the epoch was processed WITH an error the enter again cron iteration
The SQL query will only update on duplicated exception if there is no error. If there is an error then do not update row in db. Althought this last situation should never happen

Store `trackValidatorsPerformance`error in db 

---

packages/ui/src/App.tsx
packages/ui/src/components/TopBar/ToolBar.tsx
packages/ui/src/components/ValidatorsImport/ValidatorsImport.tsx
packages/ui/src/components/ValidatorsPerformance/ValidatorsPerformance.tsx

Implement route `/validatorsPerformance` route in frontend. The new route will be available from the toolbar. The way it will work is:
- When clicking on the button to redirect to the `/validatorsPerformance` route, the URL will be built with all the validator indexes/pubkeys as query parameters of the URL, so the performance UI will be shown for all the validators loaded in the brain
- Furthermore, when the user clicks on the existing icon for beaconcha.in with a preset of validators selected there will be shown a pop-up where the user will be able to choose between: "Local validators performance" vs "Remote validators performance - beaconcha.in". In both scenarios the URL will be built with the validators indexes/pubkeys selected as query parameters.

Implement route `/validatorsPerformance` route

---

packages/ui/src/App.tsx
packages/ui/src/ImportScreen.tsx
packages/ui/src/components/TopBar/ToolBar.tsx
packages/ui/src/components/ValidatorsPerformance/ValidatorsPerformance.tsx

Reverts dappnode/StakingBrain#343

Revert "Implement route `/validatorsPerformance` route"

---

packages/brain/src/modules/apiClients/postgres/index.ts
packages/brain/src/modules/validatorsDataIngest/index.ts

Use types in postgres:
- Data return
- Columns

Use types in postgres

---

packages/brain/src/modules/apiClients/beaconchain/index.ts
packages/brain/src/modules/cron/trackValidatorsPerformance/getActiveValidatorsLoadedInBrain.ts
packages/brain/test/unit/modules/ cron/trackValidatorsPerformance/getActiveValidatorsLoadedInBrain.unit.test.ts

- revert `getStateValidator` to being a GET again
- fetch all validator indexes from beaconchain instead of going one by one

improve fetching indexes from beaconchainapi

---

packages/brain/src/modules/cron/trackValidatorsPerformance/insertPerformanceData.ts
packages/brain/src/modules/cron/trackValidatorsPerformance/sendValidatorsPerformanceNotifications.ts
packages/brain/src/modules/cron/trackValidatorsPerformance/trackValidatorsPerformance.ts

Refactor notifications:
- danger -> missed block proposal
- warning -> missed attestation
- success -> block proposed
It will send notification only if epoch has been processed without an error to avoid spamming on every iteration if there is an error (corn retries on error and exits if succeeds)

Refactor notifications

---

packages/brain/src/modules/cron/trackValidatorsPerformance/fetchAndInsertValidatorsPerformanceData.ts
packages/brain/src/modules/cron/trackValidatorsPerformance/index.ts
packages/brain/src/modules/cron/trackValidatorsPerformance/sendValidatorsPerformanceNotifications.ts

Reorg validators performance cron backend code:
- Split cron functions into separated files
- Remove `lastEpochProcessedWithError`
- Move `lastProcessedEpoch` to other file
This approach makes code looks cleaner and simpler while having the same functionality

Reorg validators performance cron backend code

---

packages/brain/src/modules/config/getValidatorToken.ts
packages/brain/test/unit/modules/apiClients/cron.unit.test.ts
packages/brain/test/unit/modules/apiClients/validatorApi.unit.test.ts
packages/brain/test/unit/modules/db/index.unit.test.ts

Update Prysm validator API token for v5.1.0 which requires a token that follows a defined standard, not complied by the current one. Needs to be released together with: https://github.com/dappnode/DAppNodePackage-prysm-generic/pull/7

Update Prysm 5.1.0 token

---

packages/brain/src/index.ts
packages/brain/src/modules/apiClients/index.ts
packages/brain/src/modules/apiClients/prometheus/error.ts
packages/brain/src/modules/apiClients/prometheus/index.ts
packages/brain/src/modules/apiClients/prometheus/types.ts
packages/brain/src/modules/apiClients/standard.ts
packages/brain/src/modules/cron/trackValidatorsPerformance/fetchAndInsertEpochValidatorsData.ts
packages/brain/src/modules/cron/trackValidatorsPerformance/index.ts
packages/brain/src/modules/cron/trackValidatorsPerformance/sendValidatorsPerformanceNotifications.ts

Add prometheus client and collect host metrics for notifications:
- warning: validator missed attstation
- danger: validator missed proposing a block
The host metrics are collected 
- Average CPU temp
- Average CPU usage
- Average memory usage
- Disk IO utilization

Implement prometheus api client

---

packages/brain/src/modules/config/index.ts

nimbus gnosis still doesnt have separated images for beaconchain and validator. see:
https://github.com/gnosischain/gnosis-nimbus-eth2/issues/1

Use legacy beacon-validator for nimbus gnosis

---

packages/brain/src/index.ts
packages/brain/src/modules/apiServers/brain/config.ts
packages/brain/src/modules/apiServers/brain/startBrainApi.ts
packages/brain/src/modules/apiServers/index.ts
packages/brain/src/modules/apiServers/launchpad/config.ts
packages/brain/src/modules/apiServers/launchpad/startLaunchpadApi.ts
packages/brain/src/modules/apiServers/ui/config.ts
packages/brain/src/modules/apiServers/ui/startUiServer.ts
packages/brain/src/modules/config/index.ts
packages/brain/src/modules/config/loadEnvs.ts
packages/brain/src/modules/config/types.ts

Add allowed origin env to enable setting a custom cors. Its format must be a string comma separated of the allowed origins desired, or the wildcard "*"

Add allowed origin env

---

packages/brain/src/modules/apiServers/brain/startBrainApi.ts
packages/brain/src/modules/apiServers/index.ts
packages/brain/src/modules/apiServers/launchpad/startLaunchpadApi.ts
packages/brain/src/modules/apiServers/ui/startUiServer.ts
packages/brain/src/modules/config/loadEnvs.ts
packages/brain/src/modules/config/types.ts

Use first origin from brain  when reading cors if length 1

Use first origin from brain 

---

packages/brain/src/modules/apiServers/ui/calls/exitValidators.ts
packages/brain/src/modules/apiServers/ui/calls/index.ts
packages/brain/src/modules/apiServers/ui/calls/types.ts

Fix get exit validators

---

packages/brain/src/modules/apiClients/signer/index.ts
packages/brain/src/modules/cron/reloadValidators/index.ts

Check signer api upcheck endpoint instead of healthcheck

Check signer api upcheck endpoint in cron `reloadValidators`

---

packages/brain/src/modules/config/index.ts

Supose nimbus is monoservice if network is set to gnosis. Needed because gnosis is not yet generic

fix nimbus gnosis

---

.github/workflows/main.yml
.github/workflows/release.yml
Dockerfile
Dockerfile.brain.dev

This PR adds ARM support for StakingBrain in preparation of adding ARM support to the Web3Signer package.

Add arm support

---

packages/ui/src/ImportScreen.tsx
packages/ui/src/components/Dialogs/EditFeesDialog.tsx
packages/ui/src/components/Dialogs/KeystoresDeleteDialog.tsx
packages/ui/src/components/Dialogs/KeystoresExitDialog.tsx
packages/ui/src/components/StakerConfig/StakerConfig.tsx
packages/ui/src/components/TopBar/ToolBar.tsx
packages/ui/src/components/ValidatorList/KeystoresDataGrid.tsx
packages/ui/src/components/ValidatorList/ValidatorList.tsx

- Improved minimal styles (e.g., Topbar logo, Layout, and Cards)
- Validators screen responsive
- Full-screen dialogs on mobile
- Import Screen responsive

Responsive brain
